[workspace]
members = [
  "programs/stablecoin-core",
  "programs/transfer-hook",
]

[programs.localnet]
stablecoin_core = "DNU6Zz4eBYdh5gMGppGrGXMjA3atST2dSsiX6XZCF7v1"
transfer_hook = "4eY1C8wjyJXTA3zUju9tKmND1netsJw9ViW7uBRCdzGQ"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
