[workspace]
members = [
  "programs/stablecoin-core",
  "programs/transfer-hook",
]

[programs.localnet]
stablecoin_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgMQVGKZ2H3m"
transfer_hook = "8opHzTAnfzRpPEx21XtnrVTX28YQuCpAjcn1PczScKh"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
