[workspace]
members = [
  "programs/stablecoin-core",
  "programs/transfer-hook",
]

[programs.localnet]
stablecoin_core = "5oaQNq7VZWRzaqhY7vxaxnP5fjoGCM6266LkSk8mjJS4"
transfer_hook = "ANsBbf6d6k7gtaj2mWC8d4eLz5FTkDLvmmLkQuxR7aUF"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
